name: notify-packager

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string        
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "notify version ${{ inputs.version }}"
      - run: test -n "${{ secrets.PACKAGER_TOKEN }}"
  call-packager:
    uses: Composable-Build/repo-packager/.github/workflows/rebuild-packages.yml@main
    with:
      repo: ${{ inputs.repo }}
      tag: ${{ inputs.tag }}
    secrets:
      PACKAGER_TOKEN: ${{ secrets.PACKAGER_TOKEN }}